18F/uswds-jekyll

- _includes/components/footer.html
- jekyll-uswds.gemspec
> Fix footer logo.url reference

- _includes/components/footer.html
- jekyll-uswds.gemspec
Once more, with _feeling!_
Bumps to v0.3.2.
> Fix footer URL (again)

- _includes/meta.html
> Add viewport, charset, and X-UA-Compatible meta

- _includes/components/footer.html
**Why**: This does not appear to be a valid USWDS grid class
> Remove usa-width-one-fifth

- README.md
- _data/footer.yml
- _data/navigation.yml
- _includes/components/footer.html
- _includes/components/header.html
- _includes/sidenav.html
- _includes/subnav.html
Added logic to allow for rendering of external links by specifying `external: true` for link.
Also updated the documentation and default navigation to have examples of this.
> Support for external links

- demo/landing.html
Fixes issue https://github.com/18F/uswds-jekyll/issues/36
> Remove usa-section and usa-grid divs

- _includes/components/banner.html
Updating USA banner language from https://components.standards.usa.gov/components/detail/banner.html
> Updating USA banner language

- Gemfile.lock
- Rakefile
- uswds-jekyll.gemspec
Bump the version to 1.4.1 and include Rake tasks for publishing to Ruby gems
Refs #5
> Publish to rubygems

- CONTRIBUTING.md
- README.md
Creating this PR from @jeremiak work on pushing new releases to rubygems
> Add documentation about releasing

- _data/navigation.yml
- _includes/components/header--basic.html
- _includes/components/header--extended.html
See issue https://github.com/18F/uswds-jekyll/issues/46 for details
> Fixing pipe `|` in secondary nav issue and updating external link if statement

- _includes/subnav.html
Fix for https://github.com/18F/uswds-jekyll/issues/71
> Remove relative_url filter from anchor links

- pages/404.md
Adding default 404 page to the pages directory. 
Addresses issue #81
> Adding default 404 page

- README.md
> Adding instruction for last modified date

- README.md
- _data/footer.yml
- uswds-jekyll.gemspec
See this post for details
https://designsystem.digital.gov/whats-new/updates/2018/01/17/changing-our-name/
> Updating `standards` in USWDS to `system`

- README.md
- _config.yml
Adding to the documentation and cleaning up a bit of the documentation as well.
> Adding anchor js documentation

- demo/home.html
- demo/page.md
**Preview:** https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-add-links/
Adding a few links to various sections of the demo pages to show what links would look like in those sections.
> Adding links to demo pages

- _config.yml
- _layouts/default.html
- _sass/components/_site-width.scss
- assets/css/main.scss
To preview get locally and uncomment the `site_width` variable found in the `_config.yml`
> Add ability to set the site width to 100%

- _config.yml
- package-lock.json
- package.json
This pull request updates the site to use USWDS 1.6.0 by changing the package.json (#132) and compresses sass (#125).
I hope this helpful!
> Update USWDS and sass compress

- _data/header.yml
- _data/navigation.yml
- _includes/components/header--basic-mega-menu.html
- _includes/components/header--extended-mega-menu.html
- _includes/header.html
Add extended mega menu as an option to set in the header.yml config file 
To preview - view locally and set the header type to `extended-mega`, `basic-mega`
**To do before merging**
> Add extended header mega menus as an option

- package-lock.json
- package.json
Fixing the cached-path-relative issue
> Fix cached-path-relative issue

- _data/header.yml
- _includes/components/header.html
- _sass/components/_header.scss
- assets/css/main.scss
Potential implementation for #124.
I used the `display-icon` helper from the USWDS files, but I'm not super happy about passing a blank icon filename and then overriding it.
> Adds an optional header logo to header.yml

- README.md
Another type of migration that has been / needs to be done across various repositories.
> link to pull request showing migration from guides_style_18f

- README.md
A couple small spelling tweaks.
> Spelling fixes for README

- CONTRIBUTING.md
- _config.yml
https://github.com/18F/tts-tech-portfolio/issues/519
Rename default branch master -> main
> Update default branch
