18F/uswds-jekyll

- _config.yml
- _includes/scripts.html
- _includes/styles.html
- jekyll-uswds.gemspec
My colleagues @gemfarmer and @line47 ran into an issue using the theme today in which the CSS and JS weren't loading, and after a bit of digging I realized that I hadn't documented the need to manually copy the `styles` and `scripts` config entries from [this repo's `_config.yml`](https://github.com/18F/jekyll-uswds/blob/6caf418158a1311d94fcbb5d75d653ede6968a74/_config.yml#L3-L8). Whoops!
My solution for this issue is eliminate the requirement for those config keys and have both the [styles](https://github.com/18F/jekyll-uswds/blob/master/_includes/styles.html) and [scripts](https://github.com/18F/jekyll-uswds/blob/master/_includes/scripts.html) includes use USWDS assets by default if they aren't provided.
Because we want the JS to be async and there's no easy way create objects in Liquid …
> Use USWDS CSS and JS by default

- README.md
- _includes/styles.html
- jekyll-uswds.gemspec
Thanks to @hursey013 for pointing out a typo in the stylesheets include that was preventing custom styles in `_config.yml` from being used. That's fixed, and I've added a new "Assets" heading to the docs that includes some notes about the default CSS and JS, then leads into how to override them.
Brian, would you mind testing this? You should be able to reference this branch in your `Gemfile` like so:
```ruby
gem 'jekyll-uswds', :git => 'https://github.com/18F/jekyll-uswds.git', \
:branch => 'fix-default-styles'
```
Thank you!
> Fix default styles typo; add asset defaults docs

- _includes/components/footer.html
- jekyll-uswds.gemspec
This PR ensures that footer logo URLs are prefixed with `site.baseurl`, and adds support for a `url` property in `site.data.footer.logos[*]`, which wraps the image in a link.
Bumps to version 0.3.0.
> Fix footer logo image URLs; add link support

- README.md
This fixes a typo in the README for the USWDS image path variable, which should be `$image-path`, not `$img-path`.
> $img-path => $image-path

- _includes/components/header.html
It's currently linked to `#` and this makes it link to the home page.
> Update logo to link to home page

- Gemfile.lock
- _includes/components/header.html
- package.json
- uswds-jekyll.gemspec
1. Add `usa-current` class to active primary nav links
1. Allow for a header `href` property to control the site title link
1. Remove `accesskey="1"` per 18F/web-design-standards#1772
1. Add `npm start` script and `postinstall` hook to run `bundle`
@maya do you mind reviewing this one?
> More header fixes

- jekyll-uswds.gemspec
- uswds-jekyll.gemspec
Fixes #1. I've included a gemspec for the `jekyll-uswds` gem for backwards compatibility, but only projects that explicitly update their dependencies to `uswds-jekyll` will get changes from here on out.
This will bump the version to 1.0.0.
cc for visibility: @maya @hbillings @hursey013 @line47 @gemfarmer (anyone else?)
> Rename gem from `jekyll-uswds` to `uswds-jekyll`

- _includes/components/header.html
This will allow the site link to link to the home page. It needs the forward slash bc `site.baseurl` is blank by default.
> Add forward slash to logo link

- _layouts/landing.html
The landing page uses `usa-width-one-whole`, but it's not needed and can just put content inside `usa-grid`. This would also allow folks to add their own columns into this.
> Remove use of usa-width-one-whole from landing page

- _data/header.yml
- _includes/components/header--basic.html
- _includes/components/header--extended.html
- _includes/header.html
This addresses issue https://github.com/18F/uswds-jekyll/issues/21
You can set different header options by changing the `header.yml`config file.
```
type: basic
```
> Refactoring header component to add both basic and extended options

- _includes/components/footer.html
Moved decision to render footer logos out from underneath a check for contact info. This more closely matches the patterns in how footer.yml file is structured.
> Adjusted footer rendering

- _includes/components/header--extended.html
This came up on an a11y scan: `Form elements do not have associated labels.`
Looks like we have a label for the search field but it's not currently associated with the input field, so this remedies that.
> Associate label with search field

- _layouts/search-results.html
Currently it was inheriting `base` layout and that was updated to `default `in PR https://github.com/18F/uswds-jekyll/pull/40 but was missed in this layout.
> Updating search-results layout to inherit default

- README.md
- _config.yml
- _data/navigation.yml
- _includes/analytics.html
- _includes/google-analytics.html
- _layouts/default.html
Followed the same format the guides-style is using for adding GA. 
This addresses https://github.com/18F/uswds-jekyll/issues/64
> Adding the option of using Google analytics

- _includes/components/header--basic.html
- _includes/components/header--extended.html
Preview: https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/no-flicker/
There is still a fade in from `usa-overlay` that will be addressed by the USWDS team. Will merge that in once it is added into an official release - https://github.com/18F/web-design-standards/pull/2275
> Fix to stop dropdowns and search box from flickering on page load

- README.md
Adding the instruction to update the Gemfile in new jekyll sites to include the 'jekyll_pages_api_search' gem. Otherwise, jekyll serve errors out.
Error received before adding the gem:
> Update new site instructions to include 'jekyll_pages_api_search' step

- _includes/components/header--basic.html
The class `usa-sr-only` was hiding the search box for the basic heading.
Removing that class and the search now shows 👍
> Show search in basic header

- README.md
Removing the step to update your layouts when creating a new site. We are now using GitHub default layouts and don't need to modify the layout names to get started with a new site.
> Remove layout modifications for new site setup 

- _includes/scripts.html
This relates to https://github.com/18F/uswds-jekyll/issues/85
It turns out that you can't currently test if a plugin is installed with Jekyll:
https://github.com/jekyll/jekyll/issues/6020
https://github.com/jekyll/jekyll/pull/6046
So rather than using the `{% jekyll_pages_api_search_load %}` tag included with https://github.com/18F/jekyll_pages_api_search, this updates the theme to directly embed the required javascript if `jekyll_pages_api_search` is defined in the _config.yml. The end result is the same as using the `{% jekyll_pages_api_search_load %}` tag - I think the main benefit of using the tag relates to using the plugin with Browserify, which is beyond the scope of the theme anyways.
> Conditionally include search javascript

- _data/header.yml
- _includes/components/header--basic.html
- _includes/components/header--extended.html
- _includes/header.html
You can now show/hide the USA banner via a config in the `header.yml`
Preview URL - https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-usa-banner/
> Making the usa banner it's own component

- _data/footer.yml
- _includes/components/footer--medium.html
- _includes/footer.html
**Preview**
https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-footer-updates/
The current implementation of the default footer was following the USWDS in some ways but needed a few modifications.
The default footer has been updated to follow the  `medium` USWDS footer option 
https://components.designsystem.digital.gov/components/detail/footer--default.html
There is another issue to add the `big` and `slim` options
https://github.com/18F/uswds-jekyll/issues/53
> Updating the default footer to closer match the USWDS

- demo/home.md
- demo/page.md
Preview: https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-add-links/
Somehow the links in the content on the demo pages are no longer in master from this PR https://github.com/18F/uswds-jekyll/pull/136
I think the issues last friday with needed to redo the theming PR we omitted this work
> Adding links back in

- _includes/styles.html
The `uniq` filter is causing issues when styles are included using `href` and `media` in the `styles` array. Fixes https://github.com/18F/uswds-jekyll/issues/47
> Remove uniq filter from styles include

- _layouts/project.html
- _layouts/team-member.html
Removing `usa-width-one-fourth` as it is not needed for the sidenav
> Removing grid from sidenav

- _data/header.yml
- _includes/components/banner.html
I'm working on some .mil websites, and want to correct an issue where the top banner argues the user should trust the website because it's a .gov.
This is one of the simpler solutions I could think of, and I note that if additional options are ever added one might want to add a JS based TLD determiner.
https://github.com/deptofdefense/code.mil/issues/182
> Add ability to customize government TLD used in banner

- README.md
- _layouts/page.html
- demo/page.md
I was surprised that the title wasn't showing as an `<h1>` automatically, so this pull request adds it.
I suppose one could argue that not all users might want this, and/or that changing the behavior for current users would be unexpected... Thoughts?
> use the page title from the frontmatter in the page itself

- _includes/components/footer--medium.html
No reason it should be dependent on the other options. Here's what it looks like (after the change) with a `footer.yml` config of
```yaml
type: medium
edit_page:
text: Edit this page
```
⬇️
> allow edit_page to be the only footer option specified

- _data/footer.yml
- _data/navigation.yml
- _includes/components/footer--big.html
- _includes/components/footer--slim.html
- _includes/footer.html
Closes #53 
This PR introduces the ability to use the Slim and Big variations for the footer. I modeled this off of the way that header variations are selected.
I'm not positive if it's the best way to do it, but I added a new group in `_data/navigation.yml` for the Big footer's topic headers and links. I don't love that it necessitates editing a second value in `_data/footer.yml`, but hopefully the comment I left about it and moving that `links` value right up under it makes it clear enough for people. Let me know if you'd like me to try something different.
Happy Hacktoberfest! 🎃
> Add Slim and Big footer variations

- README.md
Setting the `styles` in the `_config.yml` doesn't stop the site from loading the default stylesheet, so just have that path match.
https://github.com/18F/uswds-jekyll/blob/9063de07ce09e308437eefba8f8d45f77ea2a9e2/_includes/styles.html#L2-L6
I suggest viewing the diff [ignoring whitespace](https://github.com/18F/uswds-jekyll/pull/172/files?w=1).
> correct SASS customization documentation

- _layouts/home.html
This whole chunk had been missing from the demo site, meaning users weren't able to include any `<main>` content on their homepages using that template.
> fix display of the main content in the homepage template

- _config.yml
- _includes/components/footer--big.html
- _includes/components/footer--medium.html
- _includes/components/footer--slim.html
- _includes/components/github-edit.html
This works around a weird problem, where the presence of a "github" key in the _config.yml file prevents remote_theme from working on GitHub pages. More detail [here](https://github.com/benbalter/jekyll-remote-theme/issues/32). The workaround here is to use "github_info" instead.
~~This is obviously a breaking change (albeit not so bad), but I don't see any way to maintain backwards compatibility and still fix the problem.~~ Correction: figured out a way to keep backwards-compatibility.
This also splits the link into a sub-component, to avoid repetition. This makes it easier for sites to override this link, in case they want to link to something like Prose.io instead of Github.com.
Fixes #174
> github_info instead of github to support remote_theme on GitHub Pages

- _includes/analytics.html
Per their setup page, "Global Site Tag (gtag.js) and Google Tag Manager are the recommended tracking methods for new implementations." Additional bonus is that it can be used to verify sites for Google Search Console.
Not sure if there are downsides.
https://developers.google.com/analytics/devguides/collection/gtagjs/migration
> migrate from Google Analytics' analytics.js to gtag.js

- README.md
- _includes/components/header.html
- _includes/components/search.html
- _includes/scripts.html
- Made the search configuration key consistent
- ~~Got rid of the search.gov autocomplete - didn't seem to be showing up anyway~~
- Fixed the search box not appearing when using the `extended` headers
**Before:**
**After:**
Discovered while working on https://github.com/18F/handbook/pull/1358.
> search fixes

- _includes/meta.html
Fixes rendering of html tags in meta title tag, such as in this example:
> Add strip_html filter to meta title

- _data/navigation.yml
I believe these incorrect example entries were unintentionally added in 9a1eac135fb282d08339aba76388e7419584b700. The sidenav doesn't support nested links or references to other named navigation lists.
> Remove incorrect examples in sidenav config

- README.md
This project's documentation is pretty sloppy. This PR goes a short way to improving it, but there's much farther to go. The general gist of these changes is that there a single directory for stylesheet-based customization: `/_sass`. This directory uses two critical files:
- `_uswds-theme-settings.scss`: The entry point for USWDS settings.
- `_uswds-theme-custom-styles.scss`: The entry point for new project Sass, overrides, etc.
USWDS settings control the design system output. Use settings to assign your theme colors, typefaces, type scale, and component styling (among other things). All the settings available to the design system are documented in [the Settings section of USWDS website](https://designsystem.digital.gov/documentation/settings/). In uswds-jekyll, we suggest including _only …
> Update readme to improve customization instructions

- _sass/uswds/components/_header.scss
- _sass/uswds/components/_nav-buttons.scss
Fixes a bug called out in the USWDS Public Slack.
- Removes the `$color-white` variable from the code and replaces it with the proper color token.
- Replaces `@media` with the USWDS `@include at-media()`
> Replace deprecated variables and rules

- Gemfile.lock
- uswds-jekyll.gemspec
Sites using uswds-jekyll 5.2.0+ require autoprefixer, which requires execjs, which require a JavaScript runtime, which requires installation on the user side to avoid [the "Could not find a JavaScript runtime" error](https://app.circleci.com/pipelines/github/18F/before-you-ship/69/workflows/c0eecfaa-cf95-4826-b6af-f7bc0f619f20/jobs/285). Rather than them have to make decisions or troubleshoot, this makes it simpler by including a (possibly redundant) JS runtime in the theme itself. This will automatically get pulled in as a sub-dependency on sites that use the theme, making the upgrade to 5.2.0+ seamless.
> include mini_racer as a dependency

- README.md
- _data/navigation.yml
- _sass/uswds/components/_side-nav.scss
- assets/css/uswds-theme.scss
Don't think we want/expect folks to override it anyway. Easiest to [review ignoring whitespace](https://github.com/18F/uswds-jekyll/pull/213/files?diff=unified&w=1).
> use default value for the sidenav breakpoint

- README.md
- _config.yml
- _includes/scripts.html
Touchpoints is a cool tool that lets federal agencies collect feedback from the public. This PR would allow a user to add a touchpoints_form_id to the _config.yml and automatically add the modal script from touchpoints. I.e.,
```
touchpoints_form_id: abcd1234
```
> Add touchpoints to the gem

- README.md
- package.json
- Fix Federalist build
- Update development instructions
Federalist updated its build so that Ruby/Bundle are not available during the
npm install phase. This causes our post install step to fail. Split out the
bundle install step to a separate npm script.
I also updated the development instructions which didn't quite make sense.
> Fix Federalist build

- Gemfile.lock
- _includes/components/banner.html
- uswds-jekyll.gemspec
Defaults the gov-banner to being hidden rather than waiting for USWDS to hide it. Bumps the minor version since it changes a behavior (thus not a patch) but in a non-breaking way (thus not major?).
Closes #256
> Default the gov-banner to hidden
